import type { ComponentType } from "react";
import {
  Anchor,
  Apple,
  Atom,
  Bell,
  Bird,
  CassetteTape,
  Castle,
  Cat,
  Cherry,
  Citrus,
  Cloud,
  CloudLightning,
  Clover,
  Coffee,
  Compass,
  Crown,
  Disc3,
  Droplet,
  Drum,
  Feather,
  Fish,
  Flame,
  Flower2,
  Gamepad2,
  Gem,
  Ghost,
  Glasses,
  Guitar,
  Headphones,
  Heart,
  Key,
  KeyboardMusic,
  Leaf,
  Lightbulb,
  Mic,
  Moon,
  Mountain,
  Music,
  Music2,
  Orbit,
  Palette,
  Piano,
  Radio,
  Rainbow,
  Rocket,
  Sailboat,
  Shell,
  Snowflake,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Tent,
  TreePine,
  Umbrella,
  Volume2,
  Waves,
  Wind,
  Zap,
} from "lucide-react";
import {
  BassTrumpetIcon,
  CelloIcon,
  ElectricGuitarIcon,
  HarpIcon,
  MadalIcon,
  NylonGuitarIcon,
  OscillatorIcon,
  TablaIcon,
  TrumpetIcon,
  UprightBassIcon,
  ViolinIcon,
} from "./instrumentIcons";

export const PRESET_ICONS: Record<string, ComponentType> = {
  piano: Piano,
  guitar: Guitar,
  bass: Zap,
  drum: Drum,
  wind: Wind,
  sax: Volume2,
  violin: ViolinIcon,
  upright: UprightBassIcon,
  keys: KeyboardMusic,
  electric: ElectricGuitarIcon,
  nylon: NylonGuitarIcon,
  cello: CelloIcon,
  harp: HarpIcon,
  trumpet: TrumpetIcon,
  bassTrumpet: BassTrumpetIcon,
  madal: MadalIcon,
  tabla: TablaIcon,
  // The Synth pad shows lucide's AudioWaveform, so presets get their own.
  waveform: OscillatorIcon,
  waves: Waves,
  music: Music,
  notes: Music2,
  mic: Mic,
  bell: Bell,
  disc: Disc3,
  headphones: Headphones,
  radio: Radio,
  speaker: Speaker,
  cassette: CassetteTape,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flame: Flame,
  snowflake: Snowflake,
  moon: Moon,
  ghost: Ghost,
  rocket: Rocket,
  sun: Sun,
  cloud: Cloud,
  leaf: Leaf,
  gem: Gem,
  crown: Crown,
  feather: Feather,
  mountain: Mountain,
  droplet: Droplet,
  bird: Bird,
  flower: Flower2,
  tree: TreePine,
  anchor: Anchor,
  atom: Atom,
  orbit: Orbit,
  umbrella: Umbrella,
  coffee: Coffee,
  compass: Compass,
  lightbulb: Lightbulb,
  palette: Palette,
  shell: Shell,
  cat: Cat,
  fish: Fish,
  cherry: Cherry,
  sailboat: Sailboat,
  key: Key,
  glasses: Glasses,
  apple: Apple,
  citrus: Citrus,
  clover: Clover,
  sprout: Sprout,
  rainbow: Rainbow,
  storm: CloudLightning,
  sunrise: Sunrise,
  tent: Tent,
  castle: Castle,
  game: Gamepad2,
};

// Offered by the Save picker, 48 a page: instruments, sound and gear first,
// then moods and things.
export const ICON_CHOICES = Object.keys(PRESET_ICONS);

// A preset's icon, or the key itself as text when it isn't a known icon.
export function PresetIcon({ icon }: { icon: string }) {
  const Icon = PRESET_ICONS[icon];
  return Icon ? <Icon /> : <>{icon}</>;
}
