import type { ComponentType } from "react";
import {
  Anchor,
  Atom,
  AudioWaveform,
  Bell,
  Bird,
  CassetteTape,
  Cloud,
  Coffee,
  Crown,
  Disc3,
  Droplet,
  Drum,
  Feather,
  Flame,
  Flower2,
  Gem,
  Ghost,
  Guitar,
  Headphones,
  Heart,
  KeyboardMusic,
  Leaf,
  Mic,
  Moon,
  Mountain,
  Music,
  Music2,
  Orbit,
  Piano,
  Radio,
  Rocket,
  Snowflake,
  Sparkles,
  Speaker,
  Star,
  Sun,
  TreePine,
  Umbrella,
  Volume2,
  Waves,
  Wind,
  Zap,
} from "lucide-react";
import { UprightBassIcon, ViolinIcon } from "./instrumentIcons";

export const PRESET_ICONS: Record<string, ComponentType> = {
  piano: Piano,
  guitar: Guitar,
  bass: Zap,
  drum: Drum,
  wind: Wind,
  sax: Volume2,
  violin: ViolinIcon,
  upright: UprightBassIcon,
  keys: KeyboardMusic,
  waveform: AudioWaveform,
  waves: Waves,
  music: Music,
  notes: Music2,
  mic: Mic,
  bell: Bell,
  disc: Disc3,
  headphones: Headphones,
  radio: Radio,
  speaker: Speaker,
  cassette: CassetteTape,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flame: Flame,
  snowflake: Snowflake,
  moon: Moon,
  ghost: Ghost,
  rocket: Rocket,
  sun: Sun,
  cloud: Cloud,
  leaf: Leaf,
  gem: Gem,
  crown: Crown,
  feather: Feather,
  mountain: Mountain,
  droplet: Droplet,
  bird: Bird,
  flower: Flower2,
  tree: TreePine,
  anchor: Anchor,
  atom: Atom,
  orbit: Orbit,
  umbrella: Umbrella,
  coffee: Coffee,
};

// Offered by the Save picker, two full pages of 22: instruments, sound and
// gear first, then moods and things.
export const ICON_CHOICES = Object.keys(PRESET_ICONS);

// A preset's icon, or the key itself as text when it isn't a known icon.
export function PresetIcon({ icon }: { icon: string }) {
  const Icon = PRESET_ICONS[icon];
  return Icon ? <Icon /> : <>{icon}</>;
}
